---
title: "urume_vpaチェック"
author: "chikako watanabe"
date: "2021/1/21"
output: html_document
---

```{r setup, include=FALSE}

opts_knit$set(root.dir= normalizePath("C:/RWD/ASSESS/urume/for_share"))
options(digits=15)

source("uVPA.r")
getwd()
```

# 1. vpa計算
ウルメイワシのVPAは、2020年評価の場合、2020年の1－6月までの年齢別漁獲尾数を使用する。

1.frasyrのVPAと同様、maa,caa,waaを呼び出し、frasyr::data.handler()で整形する。
2.2020年前半のFには、同齢の過去の一定期間の平均値を与える。この期間の年数をlagyrで指定する。
この2つを引数にしてcalcuVPA(dat,lagyr)で計算する。

```{r calc_VPA, echo=FALSE, warning=FALSE}

#1.データ呼び出し ----
maa   <- read.csv("./vpa_data/maa.csv", row.names = 1)
caa   <- read.csv("./vpa_data/caa.csv", row.names = 1)
waa   <- read.csv("./vpa_data/waa.csv", row.names = 1)

#2.引数の入力 ----
m     = 0.625 #半年あたりM
lagyr = 3 #直近年の後半に与えるFの計算に使用、過去何年平均にするか.

#3.データの整形 ----
##frasyrの形にする
dat = frasyr::data.handler(caa, waa,maa, M=m)

#4.計算----
# 作成したデータと、平均する年数を引数にする
res_uvpa = calcuVPA(dat,lagyr)

#5.結果の確認と保存----urume_vpa&future_HS_fore_share.xlsxのVPAシートの結果と一致するはず

res_uvpa$ssb
res_uvpa$naa
res_uvpa$Fc.at.age

#オブジェクトとして保存するとき以下を実行:あとでこのファイルからVPAの結果など取り出します
save(res_uvpa, file="./obj/res_urume_vpa.rda")
```


# 2. （参考）レトロスペクティブ解析 
単純なレトロ:データを一年ずつ落としていく

```{r retro_vpa, fig.height=6, fig.width = 8, out.width='50%'}
# レトロ用出力の関数
out_retro_uvpa = function(res){
 endyear = max(as.numeric(colnames(res$naa)))
 ny = ncol(res$naa)

  res$faa[,ny] = res$Fc.at.age

  temp = data.frame(
    year     = as.numeric(colnames(res$naa)),
    ssb      = as.numeric(res$baa[3,]),
    recruit = as.numeric(res$naa[1,]),
    wcatch  = as.numeric(colSums(res$wcaa, na.rm = TRUE)),
    fave    = as.numeric(colMeans(res$faa,na.rm=TRUE)),
    biomas   = as.numeric(colSums(res$baa[c(1,3),], na.rm = TRUE)),
    endyear = endyear
  )
  return(temp[1:(ny-1),])
  
}

#データ呼び出し(1.vpa計算のデータを引き継ぐ場合は不要） 
maa   <- read.csv("../VPA/data/maa.csv", row.names = 1)
caa   <- read.csv("../VPA/data/caa.csv", row.names = 1)
waa   <- read.csv("../VPA/data/waa.csv", row.names = 1)

# 引数の入力 :変えたいときはここで変える
m     = 0.625 #半年あたりM
lagyr = 3 #直近年の後半に与えるFの計算に使用、過去何年平均にするか.

#計算
##レトロに入る前
res_retro = list()
dat = frasyr::data.handler(caa, waa,maa, M = m)
res_retro[[1]] = calcuVPA(dat,lagyr)

##レトロループ
for(i in 1:5){
 maar = rev(rev(maa)[,-c(1:i)])
 waar = rev(rev(waa)[,-c(1:i)])

 caar = rev(caa)[,-c(1:i)]
 caar[c(2,4),1] = NA
 caar = rev(caar)
 
#データの整形 
##frasyrの形にする
 dat = frasyr::data.handler(caar, waar,maar, M = 0.625)
#計算
# 作成したデータと平均する年数を引数にしてres_VPAをリストにする
res_retro[[i+1]] =  calcuVPA(dat,lagyr)
}

## 作図用のデータ整形
dfig_retro = list()
for(i in seq_along(res_retro)){
  dfig_retro[[i]] = out_retro_uvpa(res_retro[[i]])
}
dfig_retro = do.call(rbind, dfig_retro)

dfig_retro$ssb = dfig_retro$ssb/1000
dfig_retro$biomas = dfig_retro$biomas/1000
dfig_retro$recruit = dfig_retro$recruit/1000

r1= ggplot(dfig_retro, aes(x=year, y=biomas, color=as.factor(endyear))) + geom_line(size = 1) + theme_SH()
r2= ggplot(dfig_retro, aes(x=year, y=ssb, color=as.factor(endyear))) + geom_line(size = 1) +theme_SH()
r3= ggplot(dfig_retro, aes(x=year, y=recruit, color=as.factor(endyear))) + geom_line(size = 1) +theme_SH()
r4= ggplot(dfig_retro, aes(x=year, y=fave, color=as.factor(endyear))) + geom_line(size = 1) +theme_SH()

gridExtra::grid.arrange(r1,r2,r3,r4, ncol = 2)

#saveRDS(res_retro, "./obj/vpa_retro_original.obj")
```

# 3.（参考）年齢別漁獲尾数のブートストラップ ----
frasyrの関数をウルメ用に書き直した。エラーとかには対応してない
```{r caa_boot, fig.height = 4, fig.width = 12, out.width='50%'}

#データ呼び出し （1.のデータを継承する場合は不要）
#maa   <- read.csv("./source/VPA/data/maa.csv", row.names = 1)
#caa   <- read.csv("./source/VPA/data/caa.csv", row.names = 1)
#waa   <- read.csv("./source/VPA/data/waa.csv", row.names = 1)

#.引数の入力 必要に応じて改変
m     = 0.625 #半年あたりM
lagyr = 3 #直近年の後半に与えるFの計算に使用、過去何年平均にするか.

# データの整形
##frasyrの形にする
dat = frasyr::data.handler(caa, waa,maa, M=m)

#vpa計算
res = calcuVPA(dat, lagyr)

#ブートストラップの準備
B_ite = 100
B_cv = 0.2
ci_range = 0.95 

# 誤差をあたえたcaaの生成
year <- colnames(res$input$dat$caa) %>% as.numeric()
age <- rownames(res$input$dat$caa) %>% as.numeric()
caa_base <- res$input$dat$caa %>% unlist() %>% as.numeric()
caa_boot <- list()

for (i in 1:length(caa_base)) caa_boot[[i]] <- exp(log(caa_base[i]) + rnorm(B_ite, -0.5 * B_cv, B_cv))

name_tmp <- list()
tmp <- numeric()

for (i in 1:length(year)) {
  for (j in 1:length(age)) {
    tmp[j] <- paste0("age", age[j], "_", year[i])
  }
  name_tmp[[i]] <- tmp
}

names(caa_boot) <- unlist(name_tmp)

input0 <- res$input
input0$plot <- FALSE
tmp <- numeric()
ssb_mat <- abund_mat <- biomass_mat <- matrix(NA, ncol = length(year),nrow = B_ite) #abund = recruit

for (i in 1:B_ite) {
  for (j in 1:length(caa_boot)){
    tmp[j] <- caa_boot[[j]][i]
    }
  
  caa_tmp <- matrix(tmp, ncol = length(year)) %>% as.data.frame()
  colnames(caa_tmp) <- year
  rownames(caa_tmp) <- age
  
  bmaa = input0$dat$maa
  bwaa = input0$dat$waa
  bcaa = caa_tmp

  bdat = frasyr::data.handler(bcaa, bwaa,bmaa, M = 0.625)
  #res_tmp <- try(safe_call(calcuVPA, bdat, force = TRUE))
  
  res_tmp = calcuVPA(bdat,lagyr = 3)
  
  #if (class(res_tmp) == "try-error") {
  #  message(paste("Iteration", i, "was errored ...",sep = " "))
  #  ssb_mat[i, ] <- rep(NA, length(year))
  #  abund_mat[i, ] <- rep(NA, length(year))
  #  biomass_mat[i, ] <- rep(NA, length(year))
  #}
  #else {
  
    ssb_mat[i, ] <- colSums(res_tmp$ssb) #SSB
    abund_mat[i, ] <- as.numeric(res_tmp$naa[1, ]) #recruit = naa1
    biomass_mat[i, ] <- colSums(res_tmp$baa[c(1,3),]) #biomass = baa[c(1,3),]
    #message(paste("Iteration", i, "has done ...", 
    #              sep = " "))
}


PB_value <- c((1 - ci_range)/2, 0.5, 1 - (1 - ci_range)/2)

d_ssb     <- t(apply(ssb_mat,     2, quantile, probs = PB_value, na.rm = T))
d_abund   <- t(apply(abund_mat,   2, quantile, probs = PB_value, na.rm = T))
d_biomass <- t(apply(biomass_mat, 2, quantile, probs = PB_value, na.rm = T))

colnames(d_ssb)     <- c("Lower", "SSB",       "Upper")
colnames(d_abund)   <- c("Lower", "Abundance", "Upper")
colnames(d_biomass) <- c("Lower", "Biomass",   "Upper")

d_ssb     <- cbind.data.frame(Year = year, d_ssb)
d_abund   <- cbind.data.frame(Year = year, d_abund)
d_biomass <- cbind.data.frame(Year = year, d_biomass)

g1 <- ggplot(d_ssb, aes(x = Year, y = SSB)) + 
  geom_ribbon(aes(ymin = Lower,ymax = Upper), alpha = 0.2, fill = "blue") + 
  geom_line(size = 1.5) + 
  ylim(c(0, NA)) + 
  theme_SH()
g2 <- ggplot(d_abund, aes(x = Year, y = Abundance)) + 
  geom_ribbon(aes(ymin = Lower,ymax = Upper), alpha = 0.2, fill = "blue") + 
  ylab("Recruitment") + 
  geom_line(size = 1.5) + 
  ylim(c(0, NA)) + theme_SH()
g3 <- ggplot(d_biomass, aes(x = Year, y = Biomass)) + 
  geom_ribbon(aes(ymin = Lower, ymax = Upper), alpha = 0.2, fill = "blue") + 
  geom_line(size = 1.5) + 
  ylim(c(0, NA)) + theme_SH()

gridExtra::grid.arrange(g1,g2,g3, ncol=3)

```

